sections:
  direct_access_with_files:
    headline: Direct Access To Image (With Files Type)
    type: pages
    status: published
    layout: cards
    image:
      query: page.page_icon.toFile
    templates:
      - test
      - files
  direct_access_without_files:
    headline: Direct Access To Image (Without Files Type)
    type: pages
    status: published
    layout: cards
    image:
      query: page.page_icon.toFile
    templates:
      - test
  page_method_with_files:
    headline: Page Method To Image (With Files Type)
    type: pages
    status: published
    layout: cards
    image:
      query: page.displayIcon
    templates:
      - test
      - files
  page_method_without_files:
    headline: Page Method To Image (Without Files Type)
    type: pages
    status: published
    layout: cards
    image:
      query: page.displayIcon
    templates:
      - test
  all_page:
    headline: All Pages
    type: pages
    status: all
